Repository home-assistant-libs/aioshelly, pull requests merged in 2025-07, with the labels that each got.

#892 Sleeping RPC devices don't support dynamic components
  aioshelly/rpc_device/device.py
  tests/rpc_device/test_device.py
Labels: enhancement

#893 Fix Block device cit/d for older firmware versions
  aioshelly/block_device/device.py
  aioshelly/const.py
Labels: bugfix

#901 Add `zigbee_firmware` property for `RpcDevice`
  aioshelly/rpc_device/device.py
  tests/rpc_device/test_device.py
Labels: new-feature

#903 Add Shelly Plug US Gen4
  aioshelly/const.py
Labels: new-feature
