Repository home-assistant-libs/aioshelly, pull requests merged in 2025-04, with the labels that each got.

#841 Read 0 bytes when checking for script support
  aioshelly/rpc_device/device.py
  tests/rpc_device/test_device.py
Labels: bugfix

#838 Raise InvalidHostError if URL build fails
  aioshelly/common.py
  aioshelly/exceptions.py
  tests/test_common.py
Labels: bugfix

#845 Add methods for number platform
  aioshelly/rpc_device/device.py
  tests/rpc_device/test_device.py
Labels: new-feature

#839 Add methods for Blu Trv boost mode
  aioshelly/rpc_device/device.py
  tests/rpc_device/test_device.py
Labels: new-feature

#850 Add initial tests for block_device module
  tests/block_device/__init__.py
  tests/block_device/conftest.py
  tests/block_device/test_device.py
  tests/block_device/test_init.py
Labels: enhancement

#849 Move dependency lists to pyproject.toml file
  .devcontainer/Dockerfile
  README.md
  pyproject.toml
  requirements.txt
  requirements_dev.txt
  requirements_lint.txt
  script/environment.sh
Labels: ci

#851 Add `enum_set` and `text_set` methods
  aioshelly/rpc_device/device.py
  tests/rpc_device/test_device.py
Labels: new-feature

#854 Add Shelly Dimmer Gen3 model
  aioshelly/const.py
Labels: new-feature

#856 Add `zigbee_enabled` property for RPC devices
  aioshelly/rpc_device/device.py
  tests/rpc_device/fixtures/shellymini1gen4/Shelly.GetComponents
  tests/rpc_device/fixtures/shellymini1gen4/Shelly.GetConfig
  tests/rpc_device/fixtures/shellymini1gen4/Shelly.GetDeviceInfo
  tests/rpc_device/fixtures/shellymini1gen4/Shelly.GetStatus
  tests/rpc_device/test_device.py
Labels: new-feature

#857 Migrate shelly to use habluetooth _async_on_raw_advertisement API
  aioshelly/ble/backend/scanner.py
  aioshelly/ble/parser.py
  pyproject.toml
  tests/ble/backend/__init__.py
  tests/ble/backend/test_scanner.py
  tests/ble/conftest.py
  tests/ble/test_init.py
  tests/ble/test_parser.py
Labels: enhancement

#860 Bump bluetooth-data-tools to 1.28.0
  pyproject.toml
Labels: dependencies
